version: 0.1
phases:
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  deploy:
    commands:
      - echo Build started on `date`
      - sls deploy --stage "prod"
